name: hazari_app
description: Hazari Labour Management

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0

  # Camera and Location
  camera: ^0.10.5+5
  camera_web: ^0.3.2+2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

  # Utils
  intl: ^0.20.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
